### ISSUE TITLE
Why use different strategy in choosing topic words in training & testing?

### ISSUE THREAD

**Issue by Evan-Gao** [victorywys/Learning2Ask_TypedDecoder#1]
Why use different strategy in choosing topic words in training & testing?

**Comment by victorywys** [comment]
Sorry, I haven't noticed this is a github issue and replied to the e-mail notification. I don't know whether you have received my answer. Here is the original copy of the e-mail:

Because topic words predicted by PMI aren't always shown in the training data. If using such words for training, the model can't learn the type probability correctly. However, when testing, we can't figure out which words will be contained in the questions. So we should predict some words in advance and treat them as topic words.
Hope it helps and thank you for your interests!
